### ISSUE TITLE
ensemble.tsv error

### ISSUE THREAD

**Issue by sugyun** [bioinform/neusomatic#19]
Hello.
When I try to make .tsv file for ensemble mode using SomaticSeq.Wrapper.sh, I encounter below error.
"""
This SomaticSeq.Wrapper.sh script is being obsolesced.
It is only here to maintain compatibility with previous versions.
You should look into run_parallel.py or somaticseq/run_somaticseq.py in the future.
This script simply runs the somaticseq/run_somaticseq.py script.

2018-10-18 10:05:36,629 - SomaticSeq - INFO - SomaticSeq Input Arguments: output_directory=/hdd8tb/sgan/29-O, genome_reference=/hdd8tb/sgan/ucsc.hg19.fasta, truth_snv=None, truth_indel=None, classifier_snv=None, classifier_indel=None, pass_threshold=0.5, lowqual_threshold=0.1, homozygous_threshold=0.85, heterozygous_threshold=0.01, minimum_mapping_quality=1, minimum_base_quality=5, minimum_num_callers=0.5, dbsnp_vcf=dbsnp.GRCh38.vcf, cosmic_vcf=None, inclusion_region=region.bed, exclusion_region=None, threads=1, keep_intermediates=False, somaticseq_train=False, tumor_bam_file=/hdd8tb/sgan/29-O.recal.bam, normal_bam_file=/hdd8tb/sgan/29-N.recal.bam, tumor_sample=TUMOR, normal_sample=NORMAL, mutect_vcf=None, indelocator_vcf=None, mutect2_vcf=MuTect2.vcf, varscan_snv=VarScan2.snp.vcf, varscan_indel=VarScan2.indel.vcf, jsm_vcf=None, somaticsniper_vcf=SomaticSniper.vcf, vardict_vcf=VarDict.vcf, muse_vcf=MuSE.vcf, lofreq_snv=None, lofreq_indel=None, scalpel_vcf=None, strelka_snv=somatic.snvs.vcf.gz, strelka_indel=somatic.indels.vcf.gz, tnscope_vcf=None, platypus_vcf=None, which=paired
sh: 1: intersectBed: not found
Traceback (most recent call last):
  File "/home/sgan/software/somaticseq/somaticseq/run_somaticseq.py", line 361, in <module>
    keep_intermediates = runParameters['keep_intermediates'] )
  File "/home/sgan/software/somaticseq/somaticseq/run_somaticseq.py", line 58, in runPaired
    outSnv, outIndel, intermediateVcfs, tempFiles = combineCallers.combinePaired(outdir=outdir, ref=ref, tbam=tbam, nbam=nbam, inclusion=inclusion, exclusion=exclusion, mutect=mutect, indelocator=indelocator, mutect2=mutect2, varscan_snv=varscan_snv, varscan_indel=varscan_indel, jsm=jsm, sniper=sniper, vardict=vardict, muse=muse, lofreq_snv=lofreq_snv, lofreq_indel=lofreq_indel, scalpel=scalpel, strelka_snv=strelka_snv, strelka_indel=strelka_indel, tnscope=tnscope, platypus=platypus, keep_intermediates=True)
  File "/home/sgan/software/somaticseq/somaticseq/../somaticseq/combine_callers.py", line 237, in combinePaired
    mod_mutect2.convert(mutect2_in, snv_mutect_out, indel_mutect_out, False)
  File "/home/sgan/software/somaticseq/somaticseq/../vcfModifier/modify_MuTect2.py", line 69, in convert
    normal_index = header.index(normal_name) - 9
UnboundLocalError: local variable 'normal_name' referenced before assignment
"""
I use Python 3.6.3.

How could I fix this error? Do I did anything wrong?

**Comment by litaifang** [comment]
My guess is that modify_MuTect2.py script is expecting MuTect2.vcf file from GATK4. If it's from GATK3, this is the email I went to a previous user:

> I think the reason is that my program assumes GATK4's MuTect2, where the header includes information regarding tumor/normal sample names, i.e., 
> ##normal_sample=WGS_NS_N
> ##tumor_sample=WGS_NS_T
> 
> It's probably better to use GATK4's mutect2. It's quite a bit faster, too.
> 
> You can also try to add those two lines to your mutect2's header, i.e., 
> **##normal_sample=NORMAL
> ##tumor_sample=TUMOR**
> 
> So it'll know which column is tumor/normal.

**Comment by msahraeian** [comment]
@sugyun If you have access to docker, there is a dockerized solution available to run all individual tools and merge their output, documented at https://github.com/bioinform/neusomatic/tree/master/ensemble_docker_pipelines

**Comment by sugyun** [comment]
@msahraeian Thank you for your reply. Your answer is very helpful! :>
