### ISSUE TITLE
fails in run_test.sh for "No such file 'work_standalone/work_tumor_without_q/work.0/count.bed''

### ISSUE THREAD

**Issue by mingyi-wang** [bioinform/neusomatic#28]
Hi,
I tried to run run_test.sh but it fails in the ERROR as following:
ERROR 2018-12-06 16:04:59,978 scan_alignments      No such file 'work_standalone/work_tumor_without_q/work.0/count.bed'
Traceback (most recent call last):
  File "/mnt/nfs/gigantor/ifs/DCEG/Resources/Tools/neusomatic/neusomatic/neusomatic/python/scan_alignments.py", line 120, in scan_alignments
    outputs = pool.map_async(run_scan_alignments, map_args).get()
  File "/DCEG/Resources/Tools/Anaconda/Anaconda2-5.3.0/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IOError: No such file 'work_standalone/work_tumor_without_q/work.0/count.bed'
Traceback (most recent call last):
  File "/DCEG/Resources/Tools/neusomatic/neusomatic/neusomatic/python/preprocess.py", line 359, in <module>
    args.scan_alignments_binary)
  File "/DCEG/Resources/Tools/neusomatic/neusomatic/neusomatic/python/preprocess.py", line 208, in preprocess
    calc_qual=False, dbsnp_regions=[])
  File "/DCEG/Resources/Tools/neusomatic/neusomatic/neusomatic/python/preprocess.py", line 50, in process_split_region
    calc_qual=calc_qual)
  File "/mnt/nfs/gigantor/ifs/DCEG/Resources/Tools/neusomatic/neusomatic/neusomatic/python/scan_alignments.py", line 126, in scan_alignments
    raise Exception
Exception

How to fix that?
Thanks,

**Comment by msahraeian** [comment]
@zyywmy happy to see your interest in NeuSomatic. Would you please run the latest release and try again? If it does not work, please send me the log again. You can also try the docker version, by running `docker_test.sh`
