### ISSUE TITLE
RuntimeError: The size of tensor a (26) must match the size of tensor b (3) at non-singleton dimension 0 (call.py)

### ISSUE THREAD

**Issue by kiranchari** [bioinform/neusomatic#33]
I'm getting this RunTimeError when I run call.py in call mode. I am using python3.7, torch==1.0.1 and torchvision==0.2.2 as listed in the README file.

Here is the traceback:

Traceback (most recent call last):
  File "call.py", line 595, in <module>
    raise e
  File "call.py", line 590, in <module>
    use_cuda)
  File "call.py", line 518, in call_neusomatic
    net, vartype_classes, call_loader, out_dir, model_tag, use_cuda)
  File "call.py", line 67, in call_variants
    for data in loader_:
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/kiran/neusomatic/neusomatic/python/dataloader.py", line 393, in __getitem__
    matrix = self.transform(matrix)
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/kiran/neusomaticenv/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The size of tensor a (26) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by msahraeian** [comment]
@kiranchari As listed in the README the torchvision version should be 0.2.1. I suspect that is the reason. Can you try downgrading that?

**Comment by kiranchari** [comment]
downgrading torchvision to 0.2.1 worked, thanks.

**Comment by kiranchari** [comment]
Hi @msahraeian, I have a question regarding something in the paper. Would you please explain what you mean by "extrapolated precision" when benchmarking the real datasets? It sounds like the definition is tied to the output of other callers? Thanks!

**Comment by msahraeian** [comment]
@kiranchari In the absence of real cancer samples with comprehensive ground truth, we are limited to measure sensitivity, and we are unable to accurately measure precision. So, we went one step further and also reported "extrapolated precision" as the percentage of predicted somatic mutations that have been called by at least two stand-alone methods, or have been reported as verified somatic mutations in at least two samples of the same cancer type in COSMIC database. We then compute extrapolated F1-score based on the harmonic mean of recall and this extrapolated precision. 
As you said, it may be biased towards the other callers output to some extent. Hopefully, in future there are more comprehensive ground truth references available to better assess different techniques on real data.
