### ISSUE TITLE
ValueError: Image must be a numpy error

### ISSUE THREAD

**Issue by ozlemmuslu** [bioinform/neusomatic#36]
Hi,

I am trying to run NeuSomatic with CUDA, I have all the right versions of libraries installed, C++ binaries created, but when I run run_test.sh I get the following error:

> ERROR 2019-04-04 12:03:19,757 __main__             Traceback (most recent call last):
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 590, in <module>
    use_cuda)
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 518, in call_neusomatic
    net, vartype_classes, call_loader, out_dir, model_tag, use_cuda)
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 92, in call_variants
    imwrite(file_name, non_transformed_matrices[i, :, :, 0:3])
  File "/code/Anaconda/3/2018/lib/python3.7/site-packages/imageio/core/functions.py", line 255, in imwrite
    raise ValueError("Image must be a numpy array.")
ValueError: Image must be a numpy array.

> ERROR 2019-04-04 12:03:19,757 __main__             Aborting!

> ERROR 2019-04-04 12:03:19,757 __main__             call.py failure on arguments: Namespace(batch_size=100, candidates_tsv=['work_standalone/dataset/work.0/candidates_0.tsv'], checkpoint='/code/neusomatic/0.2.0/neusomatic/models/NeuSomatic_v0.1.0_standalone_Dream3_70purity.pth', ensemble=False, lowqual_threshold=0.4, max_load_candidates=100000, num_threads=1, out='work_standalone', pass_threshold=0.7, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa')
Traceback (most recent call last):
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 595, in <module>
    raise e
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 590, in <module>
    use_cuda)
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 518, in call_neusomatic
    net, vartype_classes, call_loader, out_dir, model_tag, use_cuda)
  File "/code/neusomatic/0.2.0/neusomatic/python/call.py", line 92, in call_variants
    imwrite(file_name, non_transformed_matrices[i, :, :, 0:3])
  File "/code/Anaconda/3/2018/lib/python3.7/site-packages/imageio/core/functions.py", line 255, in imwrite
    raise ValueError("Image must be a numpy array.")
ValueError: Image must be a numpy array.

**Comment by msahraeian** [comment]
@ozlemmuslu I am happy to see your interest in NeuSomatic. Would you please share with me your conda environment info using `conda list` command?

**Comment by msahraeian** [comment]
@ozlemmuslu 
If you still have this problem, please pull master and run again.
This issue should have been is fixed in #38.

**Comment by ozlemmuslu** [comment]
Sorry, I missed your question. It works now, thanks!
