### ISSUE TITLE
undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by jingmeng-bioinformatics** [bioinform/neusomatic#49]
I ran neusomatic train.py on a remote server, but got the following errors:

Traceback (most recent call last):
  File "neusomatic-master/neusomatic/python/train.py", line 18, in <module>
    from torchvision import transforms
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /public/home/**/.conda/envs/**/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 

I tried several times to install g++ on the remote server, but were not successful, so I did not run ./build.sh (which requires cmake 3.13.2 and g++ 5.4.0) on the remote server and cannot run quick test. Instead I ran ./build.sh on my local machine, and ran preprocess.py on the local machine.

**Comment by msahraeian** [comment]
@jingmeng-bioinformatics thanks for your interest in NeuSomatic. 
It seems that the error is in the `from torchvision import transforms` line, Which means that your installation of torchvision (and possibly pytorch) has some problem. 
Would you please make sure you have the right versions of all python packages installed as listed in the README.

**Comment by jingmeng-bioinformatics** [comment]
Thank you. I have removed and re-installed torchvision, and the problem is solved.
