### ISSUE TITLE
Train.py Runtime Error

### ISSUE THREAD

**Issue by apptest20** [bioinform/neusomatic#54]
Very new to NeuSomatic and get Runtime error from train.py. Helps are appreciated

CMD:  train.py --candidates_tsv  dataset/*/candidates*.tsv --out out --num_threads 10 --batch_size 100
OUTPUT: 
INFO 2020-01-31 07:34:34,124 train_neusomatic     PyTorch Version: 1.1.0
INFO 2020-01-31 07:34:34,124 train_neusomatic     Torchvision Version: 0.3.0
INFO 2020-01-31 07:34:34,165 train_neusomatic     GPU training!
INFO 2020-01-31 07:34:38,699 train_neusomatic     tag: neusomatic_20-01-31-07-34-38
.
.
. run fine to this point

INFO 2020-01-31 07:34:45,115 train_neusomatic     Number of candidater per epoch: 86022
ERROR 2020-01-31 07:34:46,082 __main__             Traceback (most recent call last):
  File "/opt/neusomatic/neusomatic/python//train.py", line 570, in <module>   use_cuda)
  File "/opt/neusomatic/neusomatic/python//train.py", line 430, in train_neusomatic   outputs, _ = net(inputs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/neusomatic/neusomatic/python/network.py", line 67, in forward     x = self.pool1(F.relu(self.bn1(self.conv1(x))))
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 26 1 3, expected input[100, 119, 5, 32] to have 26 channels, but got 119 channels instead

**Comment by msahraeian** [comment]
@apptest20 It seems that the model you are training does not match your input.
If you want to train NeuSomatic in ensemble mode you need to use option `--ensemble` and your candidate.tsv files should also have been prepared in the ensemble mode.

Here it seems that the candidates have 119 channels (so are prepared in ensemble mode), so you need to use `--ensemble` command line option when running `train.py`.

**Comment by apptest20** [comment]
Thanks msahraeian.
