### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by vymao** [bioinform/neusomatic#64]
Hi, 
I just cloned the repository and tried running the test. I am getting this error: 

```
INFO 2020-05-13 20:24:16,791 __main__             Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, filter_duplicate=False, first_do_without_qual=False, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, max_dp=100000, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=10, mode='call', normal_bam='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/normal.bam', num_threads=1, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', region_bed='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/region.bed', restart=False, scan_alignments_binary='/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/bin/scan_alignments', scan_maf=0.05, scan_window_size=2000, snp_min_af=0.05, snp_min_ao=10.0, snp_min_bq=20.0, truth_vcf=None, tsv_batch_size=50000, tumor_bam='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/tumor.bam', work='work_standalone')
INFO 2020-05-13 20:24:16,792 preprocess           ----------------------Preprocessing------------------------
INFO 2020-05-13 20:24:16,798 preprocess           Scan tumor bam (and extracting quality scores).
INFO 2020-05-13 20:24:16,799 process_split_region Scan bam.
INFO 2020-05-13 20:24:16,799 scan_alignments      -------------------Scan Alignment BAM----------------------
INFO 2020-05-13 20:24:16,833 split_region         ------------------------Split region-----------------------
INFO 2020-05-13 20:24:16,869 split_region         Total length: 33514
INFO 2020-05-13 20:24:16,882 split_region         Split 0: 33514
INFO 2020-05-13 20:24:16,882 split_region         Total splitted length: 33514
ERROR 2020-05-13 20:24:16,898 run_scan_alignments (ForkPoolWorker-1) Traceback (most recent call last):
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/scan_alignments.py", line 40, in run_scan_alignments
    raise IOError("File not found: {}".format(scan_alignments_binary))
OSError: File not found: /n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/bin/scan_alignments

ERROR 2020-05-13 20:24:16,898 run_scan_alignments (ForkPoolWorker-1) File not found: /n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/bin/scan_alignments
ERROR 2020-05-13 20:24:16,899 __main__             Traceback (most recent call last):
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 435, in <module>
    args.scan_alignments_binary)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 291, in preprocess
    dbsnp_regions=dbsnp_regions_q)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 54, in process_split_region
    calc_qual=calc_qual)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/scan_alignments.py", line 147, in scan_alignments
    raise Exception("scan_alignments failed!")
Exception: scan_alignments failed!

ERROR 2020-05-13 20:24:16,900 __main__             Aborting!
ERROR 2020-05-13 20:24:16,900 __main__             preprocess.py failure on arguments: Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, filter_duplicate=False, first_do_without_qual=False, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, max_dp=100000, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=10, mode='call', normal_bam='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/normal.bam', num_threads=1, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', region_bed='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/region.bed', restart=False, scan_alignments_binary='/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/bin/scan_alignments', scan_maf=0.05, scan_window_size=2000, snp_min_af=0.05, snp_min_ao=10.0, snp_min_bq=20.0, truth_vcf=None, tsv_batch_size=50000, tumor_bam='/n/data1/hms/dbmi/park/victor/software/neusomatic/test/tumor.bam', work='work_standalone')
Traceback (most recent call last):
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 441, in <module>
    raise e
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 435, in <module>
    args.scan_alignments_binary)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 291, in preprocess
    dbsnp_regions=dbsnp_regions_q)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/preprocess.py", line 54, in process_split_region
    calc_qual=calc_qual)
  File "/n/data1/hms/dbmi/park/victor/software/neusomatic/neusomatic/python/scan_alignments.py", line 147, in scan_alignments
    raise Exception("scan_alignments failed!")
Exception: scan_alignments failed!
```

Do you know why this is?

**Comment by vymao** [comment]
Never mind, the build works now.
